Bootstrap: docker
From: danabl/glimslib_ants:2017-2_meshtool

%post
    ldconfig

%files
    WELCOME.Singularity /usr/local/share/WELCOME

%runscript
    cat /usr/local/share/WELCOME
    exec /bin/bash -i